export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
export PKR_VAR_arm_client_id="xxxxxxxxxxxxx"
export PKR_VAR_arm_client_secret="xxxxxxxxxxxxx"
export PKR_VAR_arm_subscription_id="xxxxxxxxxxxxx"
export PKR_VAR_arm_tenant_id="xxxxxxxxxxxxx"